import { getDevRevalidate } from '@misc/environments'

const DEFAULT_DEVELOPMENT_REVALIDATE = getDevRevalidate()
export const DEFAULT_REVALIDATE = DEFAULT_DEVELOPMENT_REVALIDATE ?? 60 * 60
export const DEFAULT_SITEMAP_REVALIDATE =
  DEFAULT_DEVELOPMENT_REVALIDATE ?? 60 * 60
export const DEFAULT_NOT_FOUND_REVALIDATE =
  DEFAULT_DEVELOPMENT_REVALIDATE ?? 5 * 60
